# Generated by Django 3.2.9 on 2022-03-24 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_rename_products_product'),
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baskets',
            new_name='Basket',
        ),
    ]
